# LoRA
lora_r: 8
lora_dropout: 0.0
target_modules:
  - down_proj

# data
train_ds_names:
- ctx_magic_number_32_128
- ctx_magic_number_128_256

val_ds_names:
- ctx_magic_number_32_128
- ctx_magic_number_128_256
